### ISSUE TITLE
On the machine with the M1 chip in Mac Pro.

### ISSUE THREAD

**Issue by kunpengVpn** [net-breaker/net-proxied#1]
A JavaScript error occurred in the main process

Uncaught Exception:
Error: Command failed: networksetup -setwebproxystate Ethernet off && networksetup -setsecurewebproxystate Ethernet off && networksetup -setftpproxystate Ethernet off && networksetup -setsocksfirewallproxystate Ethernet off && networksetup -setgopherproxystate Ethernet off && networksetup -setstreamingproxystate Ethernet off
at checkExecSyncError (node:child_process:911:11)
at Object.execSync (node:child_process:983:15)
at Object.execSync (node:electron/js2c/asar_bundle:2:12758)
at Executor.executeSync (/Users/mac/Desktop/kunpengvpn/node_modules/net-proxied/executor.js:22:40)
at /Users/mac/Desktop/kunpengvpn/node_modules/net-proxied/platform/mac.js:77:37
at Array.map (<anonymous>)
at MacProxied.disable (/Users/mac/Desktop/kunpengvpn/node_modules/net-proxied/platform/mac.js:75:31)
at clearProxy (webpack:///./src/main/netProxied.js?:46:64)
at eval (webpack:///./src/main/index.js?:27:1)

What is the problem, may I ask?

**Comment by kunpengVpn** [comment]
![{31953EED-36C0-4dd4-BF0D-3C14D5883818}](https://github.com/net-breaker/net-proxied/assets/148678149/a8c521ec-22bc-4111-bc1c-8e5c431cacd8)

**Comment by anonysoul** [comment]
Sorry for the delay, have you solved this problem?
